apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dex
    role: overlord
  name: dex-overlord
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dex
        role: overlord
    spec:
      containers:
          - image: quay.io/coreos/dex
            name: dex-overlord
            env:
              - name: DEX_OVERLORD_DB_URL
                value: postgres://postgres@dex-postgres:5432/postgres?sslmode=disable
              - name: DEX_OVERLORD_ADMIN_LISTEN
                value: http://0.0.0.0:5557
            command:
              - "sh"
              - "-c"
              - "/opt/dex/bin/dex-overlord --key-secrets=$(cat /etc/dex/key-secrets) --local-connector=local"
            ports:
            - containerPort: 5557
              name: overlord-port
            livenessProbe:
              httpGet:
                path: /health
                port: 5557
              initialDelaySeconds: 16
              timeoutSeconds: 1
            volumeMounts:
              - name: dex
                mountPath: "/etc/dex"
                readOnly: true
              - name: connectors
                mountPath: /etc/dex-connectors
      volumes:
        - name: dex
          secret:
            secretName: "dex"
        - name: connectors
          configMap:
            name: dex-connectors
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dex
    role: overlord
  name: dex-overlord
spec:
  ports:
    - port: 5557
  selector:
    app: dex
    role: overlord
