apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: postgres
  name: dex-postgres
spec:
  replicas: 1
  selector:
    app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
          - image: postgres
            name: dex-postgres
            ports:
            - containerPort: 5432
              name: postgres-port
